theme = "everforest_dark"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block" # デフォルトで block なので実際には指定する必要はない
select = "underline" 

[keys.insert]
j = { j = "normal_mode"} # jjでノーマルモードへ戻る
